version: 0.2

env:
  variables:
    SPRING_PROFILES_ACTIVE: "dev"

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Build Started
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp target/sgmrt-server.jar s3://my-eb-artifacts-bucket/sgmrt-${CODEBUILD_RESOLVED_SOURCE_VERSION}.jar

artifacts:
  files:
    - target/sgmrt-server.jar
  discard-paths: yes
