spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${DEV_REDIS_ENDPOINT}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
    org.hibernate.SQL: debug

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false

s3:
  telemetry-bucket-name: ${AWS_TELEMETRY_BUCKET}
  telemetry-directory-name: ${AWS_TELEMETRY_DIRECTORY}

jwt:
  secret: ${DEV_JWT_SECRET_KEY}
  expiration_time:
    access_token: 600000
    refresh_token: 1209600000
