spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
    org.hibernate.SQL: debug
